In [1]:
# Importing the libraries
import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator

2023-07-02 14:46:07.081150: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-02 14:46:07.141897: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-02 14:46:07.143011: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-02 14:46:08.739489: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [2]:
print(tf.__version__)

2.12.0


### Preprocessing the training set

In [3]:
#applying transformations only in training set to avoid overfitting
#we will do some simple geometrical transformations as zoom, rotations
#(geometrical transformations like transvections) to shift some pixels
#then rotation, horizontal flips,some zoom in and zoom out to modify images

#technical term is image augmentation, so the model does not overlearn

#here we will rescale, shear, zoom and flip
#1./255 apply feature scaling between 0 and 1
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)
#training_set in sinple quotes is the folder with subfolders of dog and cats
#target_size is the final size of images
training_set = train_datagen.flow_from_directory('training_set',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'binary')

Found 8000 images belonging to 2 classes.


### Preprocessing test set

In [4]:
#here we will not apply all the same transformation, we dont wanna touch the
#test images, however we need to reescale pixel
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('test_set',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'binary')

Found 2000 images belonging to 2 classes.


### Building the CNN

In [5]:
# Initialising the CNN
cnn = tf.keras.models.Sequential()

In [6]:
# Step 1 - Convolution

#conv2d --> filters is the number of feature detectors to apply
# input_shape is the input shape of your inputs, and colored pictures has 3D (RGB)
#for B/W images the last number would be 1
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=[64, 64, 3]))

In [7]:
# Step 2 - Pooling
##maxpool is the max value of that region
##poolsize is the matrix to pool
#strides the window to move
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

In [8]:
# Adding a second convolutional layer
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))

In [9]:
# Step 3 - Flattening
cnn.add(tf.keras.layers.Flatten())

In [10]:
# Step 4 - Full Connection
#as computer vision is more complex that data mining, we are gonna
#choose a larger number of hidden neurons
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))

In [11]:
# Step 5 - Output Layer
cnn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### training the CNN

In [12]:
#compiling the CNN

#adam is the stochastic gradient descent
cnn.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [13]:
# Training the CNN on the Training set and evaluating it on the Test set (instead of two steps)
cnn.fit(x = training_set, validation_data = test_set, epochs = 25)

Epoch 1/25


2023-07-02 14:46:12.427258: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]


249/250 [============================>.] - ETA: 0s - loss: 0.6790 - accuracy: 0.5752

2023-07-02 14:46:34.503693: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]


250/250 [==============================] - 25s 95ms/step - loss: 0.6790 - accuracy: 0.5751 - val_loss: 0.6007 - val_accuracy: 0.6875
Epoch 2/25
250/250 [==============================] - 22s 88ms/step - loss: 0.5878 - accuracy: 0.6856 - val_loss: 0.5994 - val_accuracy: 0.6910
Epoch 3/25
250/250 [==============================] - 22s 87ms/step - loss: 0.5404 - accuracy: 0.7250 - val_loss: 0.5417 - val_accuracy: 0.7325
Epoch 4/25
250/250 [==============================] - 22s 88ms/step - loss: 0.5135 - accuracy: 0.7444 - val_loss: 0.5135 - val_accuracy: 0.7565
Epoch 5/25
250/250 [==============================] - 23s 91ms/step - loss: 0.4918 - accuracy: 0.7615 - val_loss: 0.5400 - val_accuracy: 0.7445
Epoch 6/25
250/250 [==============================] - 22s 89ms/step - loss: 0.4732 - accuracy: 0.7724 - val_loss: 0.5096 - val_accuracy: 0.7510
Epoch 7/25
250/250 [==============================] - 22s 87ms/step - loss: 0.4555 - accuracy: 0.7831 - val_loss: 0.4587 - val_accuracy: 0.7865
Epo

In [28]:
# Part 4 - Making a single prediction

import numpy as np
#from keras.preprocessing import image
#this one change by the next one
import keras.utils as image

test_image = image.load_img('single_prediction/cat_or_dog_2.jpg', target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
#the previous was to insert it into a batch (despite it is a batch of 1)
result = cnn.predict(test_image/255.0)
#/255 is to normalize
#class indices
print("training_set.class_indices",training_set.class_indices)
if result[0][0] > 0.5:
    prediction = 'dog'
else:
    prediction = 'cat'
print(prediction)
print(result)

1/1 [==============================] - 0s 16ms/step
training_set.class_indices {'cats': 0, 'dogs': 1}
cat
[[0.04644025]]


In [29]:
print(test_image)

[[[[239. 239. 239.]
   [239. 239. 239.]
   [239. 239. 239.]
   ...
   [245. 245. 245.]
   [245. 245. 245.]
   [245. 245. 245.]]

  [[239. 239. 239.]
   [239. 239. 239.]
   [239. 239. 239.]
   ...
   [245. 245. 245.]
   [245. 245. 245.]
   [244. 244. 244.]]

  [[239. 239. 239.]
   [239. 239. 239.]
   [239. 239. 239.]
   ...
   [244. 244. 244.]
   [244. 244. 244.]
   [244. 244. 244.]]

  ...

  [[241. 217. 205.]
   [243. 220. 206.]
   [242. 219. 205.]
   ...
   [226. 201. 181.]
   [233. 205. 193.]
   [232. 215. 197.]]

  [[255. 236. 229.]
   [251. 234. 227.]
   [252. 235. 227.]
   ...
   [219. 193. 178.]
   [219. 193. 178.]
   [216. 189. 172.]]

  [[243. 230. 224.]
   [250. 235. 228.]
   [245. 232. 226.]
   ...
   [203. 180. 164.]
   [220. 198. 177.]
   [225. 202. 186.]]]]


In [31]:
test_image = image.load_img('c.jpg', target_size = (64, 64))
test_image = image.img_to_array(test_image)
test_image = np.expand_dims(test_image, axis = 0)
result = cnn.predict(test_image/255)
training_set.class_indices
if result[0][0] == 1:
    prediction = 'dog'
else:
    prediction = 'cat'
print(prediction)
print(result)

1/1 [==============================] - 0s 17ms/step
cat
[[0.9341036]]


In [17]:
test_image

array([[[[ 60.,  61.,  66.],
         [ 85.,  88.,  95.],
         [ 83.,  86.,  93.],
         ...,
         [139., 165., 136.],
         [144., 154., 163.],
         [107., 111., 114.]],

        [[126.,  98.,  95.],
         [136., 106., 104.],
         [137., 106., 104.],
         ...,
         [120., 134., 134.],
         [ 76.,  81.,  87.],
         [ 74.,  78.,  81.]],

        [[152., 112., 112.],
         [152., 111., 109.],
         [144., 106., 105.],
         ...,
         [ 73.,  83.,  85.],
         [116., 128., 126.],
         [110., 128., 128.]],

        ...,

        [[ 29.,  27.,  28.],
         [ 57.,  53.,  50.],
         [ 34.,  36.,  35.],
         ...,
         [ 81.,  65.,  66.],
         [ 83.,  69.,  69.],
         [102.,  86.,  86.]],

        [[ 15.,  15.,  15.],
         [ 42.,  37.,  31.],
         [ 51.,  47.,  48.],
         ...,
         [ 90.,  74.,  75.],
         [ 68.,  52.,  53.],
         [ 89.,  69.,  68.]],

        [[ 18.,  18.,  18.],
       